/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package GradleJavaQuickStart;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
	
	@Test
	public void testAppHasAGreeting() {
		App classUnderTest = new App();
		assertNotNull("app should have a greeting", classUnderTest.getGreeting());
	}
	
	@Test
	public void testSum() {		
		App classUnderTest = new App();
		int expected = 15;
		int number1 = 10, number2 = 5;
		int actual = classUnderTest.sum(number1, number2);
		
		assertEquals(expected, actual);
	}
}
