/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package GradleJavaQuickStart;

public class App {
	public String getGreeting() {
		return "Hello world.";
	}

	public int sum(int number1, int number2) {
		return number1 + number2;
	}

	public static void main(String[] args) {
		System.out.println(new App().getGreeting());
	}
}